use askama::Template;
use axum::{extract::State, response::{Html, IntoResponse, Redirect, Response}};
use log::info;

use crate::web::auth::AuthAdmin;
use crate::web::AppState;

// ── Templates ──

#[derive(Template)]
#[template(path = "api_docs.html")]
struct ApiDocsTemplate<'a> {
    nav_active: &'a str,
    flash: Option<String>,
    hostname: &'a str,
    api_token: Option<String>,
}

// ── Handler ──

pub async fn page(_auth: AuthAdmin, State(state): State<AppState>) -> Html<String> {
    info!("[web] GET /api — REST documentation requested");
    let api_token = state.blocking_db(|db| db.get_api_token()).await;
    let tmpl = ApiDocsTemplate {
        nav_active: "API",
        flash: None,
        hostname: &state.hostname,
        api_token,
    };
    Html(tmpl.render().unwrap())
}

pub async fn generate_token(
    auth: AuthAdmin,
    State(state): State<AppState>,
) -> Response {
    info!(
        "[web] POST /api/token/generate — generating API token for username={}",
        auth.admin.username
    );
    let token = uuid::Uuid::new_v4().to_string().replace('-', "");
    let token_for_db = token.clone();
    state
        .blocking_db(move |db| db.set_api_token(&token_for_db))
        .await;
    info!("[web] API token generated by username={}", auth.admin.username);
    let api_token = Some(token);
    let tmpl = ApiDocsTemplate {
        nav_active: "API",
        flash: Some("New API token generated. Copy it now — it will not be shown again in full.".to_string()),
        hostname: &state.hostname,
        api_token,
    };
    Html(tmpl.render().unwrap()).into_response()
}

pub async fn revoke_token(
    auth: AuthAdmin,
    State(state): State<AppState>,
) -> Response {
    info!(
        "[web] POST /api/token/revoke — revoking API token for username={}",
        auth.admin.username
    );
    state
        .blocking_db(|db| db.set_api_token(""))
        .await;
    info!("[web] API token revoked by username={}", auth.admin.username);
    Redirect::to("/api").into_response()
}

// ── Tests ──

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn api_docs_template_compiles() {
        let tmpl = ApiDocsTemplate {
            nav_active: "API",
            flash: None,
            hostname: "mail.example.com",
            api_token: None,
        };
        let rendered = tmpl.render().unwrap();
        assert!(rendered.contains("REST API"));
        assert!(rendered.contains("/api/emails"));
    }

    #[test]
    fn api_docs_template_with_token() {
        let tmpl = ApiDocsTemplate {
            nav_active: "API",
            flash: Some("Token generated".to_string()),
            hostname: "mail.example.com",
            api_token: Some("abc123token".to_string()),
        };
        let rendered = tmpl.render().unwrap();
        assert!(rendered.contains("abc123token"));
        assert!(rendered.contains("Token generated"));
    }
}
